# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Mailwing.Mailwing
PackageVersion: 1.0.1
Platform:
  - Windows.Desktop
InstallModes:
  - interactive
  - silent
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://github.com/vinaysamtani/mailwing/releases/download/v1.0.1/Mailwing.Setup.1.0.1.exe
    InstallerSha256: 3c7872eb7adfb029007a613f5e6f2bd394e7b2ec24e336d452fb4ef37f17c2ec
ManifestType: installer
ManifestVersion: 1.6.0
